name: BattleFlow App
description: "Simulate Pokémon Go PVP Battles"
full_description: |
  Take your Pokémon GO experience to the next level with BattleFlow!
  Designed for dedicated trainers, this offline-ready app offers powerful tools to help you master battles and strategize like a pro.

  ## Key Features:
  *Rankings & Recommendations*: Discover the best Pokémon for each league with up-to-date rankings and in-depth analyses.
  *Battle Simulations*: Plan your battles with detailed simulations, predicting outcomes based on your chosen Pokémon and movesets.
  *IV Checks*: Evaluate your Pokémon's individual values (IVs) to optimize your team and ensure peak performance.
  *Move Counts & Strategies*: Master the move counts for all Pokémon and uncover the best strategies to gain the upper hand in battles.
  *Offline Functionality*: All features are accessible offline, ensuring you can train and plan anytime, anywhere.
  *An account is not required*: use the app immediately after downloading. No account setup is needed.

  Whether you're a casual player or a competitive trainer, BattleFlow is your ultimate sidekick for becoming the very best, like no one ever was!
android: "https://play.google.com/store/apps/details?id=com.baru.software.oak"
iOS: "https://apps.apple.com/us/app/battleflow/id6738843812"
web: false
screenshots:
  - 1.png
  - 2.png
  - 3.png
  - 4.png
  - 5.png
